version: "3.9"
services:

  back_express_aws_ec2_docker:
    image: sodiki/back_express_aws_ec2_docker:latest
    # restart: always
    ports:
      - "3010:3010"
    volumes:
      - type: bind
        source: .
        target: /src/app
    networks:
      - serviceNetwork

networks:
  serviceNetwork:
    driver: bridge
